version: '2'
services:
  db:
    image: "postgres:11.4"
  cache:
    image: redis
  web:
    build: ./
    command: bash -c 'rm /usr/src/app/tmp/pids/server.pid; bundle exec rails s -p 3000 -b "0.0.0.0"'
    volumes:
      - ./:/usr/src/app
    volumes_from:
      - dependencies
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - db
      - cache
    environment:
      REDIS_URL: redis://cache:6379
  worker:
    build: ./
    command: bundle exec sidekiq
    volumes:
      - ./:/usr/src/app
    volumes_from:
      - dependencies
    depends_on:
      - db
      - cache
    environment:
      REDIS_URL: redis://cache:6379
  dependencies:
    # You may need to run `docker-compose build web` before this works.
    image: alpine
    command: echo "I'm a little data volume short and stdout"
    volumes:
      - /bundle
      - /node_modules
