# see https://github.com/ankane/blazer for more info

data_sources:
  main:
    url: <%= ENV["DATABASE_URL"] %>

    # statement timeout, in seconds
    # none by default
    timeout: 30

    # caching settings
    # can greatly improve speed
    # off by default
    # cache:
    #   mode: slow # or all
    #   expires_in: 60 # min
    #   slow_threshold: 15 # sec, only used in slow mode

    # wrap queries in a transaction for safety
    # not necessary if you use a read-only user
    # true by default
    # use_transaction: false

    smart_variables:
      # zone_id: "SELECT id, name FROM zones ORDER BY name ASC"
      # period: ["day", "week", "month"]
      # status: {0: "Active", 1: "Archived"}
      user_id: "SELECT id, CONCAT(full_name, ' (', email, ')') FROM users ORDER BY full_name ASC"
      event_id: "SELECT id, name FROM events ORDER BY name ASC"
      month: { 1: "January", 2: "February", 3: "March", 4: "April", 5: "May", 6: "June", 7: "July", 8: "August", 9: "September", 10: "October", 11: "November", 12: "December" }
      bank_account_id: |
        SELECT CONCAT('plaid_', plaid_account_id) AS id, CONCAT('Plaid: ', name) FROM bank_accounts WHERE should_sync_v2
        UNION
        SELECT
          DISTINCT CONCAT('increase_', increase_account_id) AS id,
          CASE increase_account_id
            WHEN 'account_phqksuhybmwhepzeyjcb' THEN 'Increase: FS Main'
            WHEN 'account_v9tdabo2us8epcz8onuq' THEN 'Increase: DAF Main'
            ELSE CONCAT('Increase: ', increase_account_id)
          END AS name
        FROM events
        UNION
        SELECT 'stripe' AS id, 'Stripe Issuing' AS name


    linked_columns:
      event_id: "/{value}"
      hcb_code: "/hcb/{value}"
      canonical_transaction_id: "/canonical_transactions/{value}"
      canonical_pending_transaction_id: "/canonical_pending_transactions/{value}"
      ip_address: "https://www.iplocation.net/ip-lookup?query={value}"
      ip: "https://www.iplocation.net/ip-lookup?query={value}"

    smart_columns:
      user_id: "SELECT id, CONCAT(full_name, ' (', email, ')') FROM users WHERE id IN {value}"
      creator_id: "SELECT id, CONCAT(full_name, ' (', email, ')') FROM users WHERE id IN {value}"
      event_id: "SELECT id, name FROM events WHERE id IN {value}"
      canonical_transaction_id: "SELECT id, CONCAT('Amount Cents: ', amount_cents, '. Memo: ', memo) FROM canonical_transactions WHERE id IN {value}"
      canonical_pending_transaction_id: "SELECT id, CONCAT('Amount Cents: ', amount_cents, '. Memo: ', memo) FROM canonical_pending_transactions WHERE id IN {value}"

# create audits
audit: true

# change the time zone
# time_zone: "Pacific Time (US & Canada)"

# class name of the user model
# user_class: User

# method name for the current user
# user_method: current_user

# method name for the display name
# user_name: name

# custom before_action to use for auth
# before_action_method: require_admin

# email to send checks from
from_email: hcb@hackclub.com

# webhook for Slack
# slack_webhook_url: <%= ENV["BLAZER_SLACK_WEBHOOK_URL"] %>

check_schedules:
  - "1 day"
  - "1 hour"
  - "5 minutes"

# enable anomaly detection
# note: with trend, time series are sent to https://trendapi.org
# anomaly_checks: trend / r

# enable forecasting
# note: with trend, time series are sent to https://trendapi.org
# forecasting: trend / prophet

# enable map
mapbox_access_token: <%= Rails.application.credentials.mapbox_access_token %>
