g_suite_mark_verifieds_job:
  cron: "*/5 * * * *" # run every 5 minutes
  class: "GSuite::MarkVerifiedsJob"

g_suite_verify_all_job:
  cron: "0 */1 * * *" # run every 1 hour
  class: "GSuite::VerifyAllJob"

g_suite_scan_verified_dns_job:
  cron: "0 12 * * *" # run every 1 day
  class: "GSuite::ScanVerifiedDnsJob"

pending_transaction_engine_nightly_job:
  cron: "0 */3 * * *" # run every 3 hour
  class: "PendingTransactionEngine::NightlyJob"

pending_event_mapping_engine_nightly_job:
  cron: "10,40 * * * *" # run every 30 minutes, but after pending_transaction_engine_nightly_job
  class: "PendingEventMappingEngine::NightlyJob"

transaction_engine_nightly_job:
  cron: "0 6 * * *" # run at 6am UTC each morning
  class: "TransactionEngine::NightlyJob"

transaction_grouping_engine_nightly_job:
  cron: "*/5 * * * *" # run every 5 minutes
  class: "TransactionGroupingEngine::NightlyJob"

event_mapping_engine_nightly_job:
  cron: "0 7 * * *" # run at 7am UTC each morning
  class: "EventMappingEngine::NightlyJob"

sync_payouts_job:
  cron: "0,30 * * * *" # run every 30 minutes
  class: "SyncPayoutsJob"

fee_reimbursement_nightly_job:
  cron: "0 1 * * *" # run every 1 day
  class: "FeeReimbursement::NightlyJob"

bank_fee_weekly_job:
  cron: "0 0 * * MON" # run first day of each week
  class: "BankFee::WeeklyJob"

disbursement_nightly_job:
  cron: "0 0 * * *" # run every 1 day.
  class: "Disbursement::NightlyJob"

disbursement_daily_job:
  cron: "0 13 * * *" # runs at 9am ET
  class: "Disbursement::DailyJob"
  queue: "default"

disbursement_hourly_job:
  cron: "*/30 * * * *" # run every 30 minutes
  class: "Disbursement::HourlyJob"

ach_transfer_nightly_job:
  cron: "*/30 * * * *" # run every 30 minutes
  class: "AchTransfer::NightlyJob"

ach_transfer_daily_job:
  cron: "0 13 * * *" # run daily at 9am ET
  class: "AchTransfer::DailyJob"

invoice_opens_to_paids_job:
  cron: "30 * * * *" # run every hour
  class: "Invoice::OpensToPaidsJob"

donation_nightly_job:
  cron: "*/30 * * * *" # run every 30 minutes
  class: "Donation::NightlyJob"

payout_nightly_job:
  cron: "0 0 * * *" # run every 1 day
  class: "Payout::NightlyJob"

reimbursement_nightly_job:
  cron: "*/5 * * * *" # run every 5 minutes
  class: "Reimbursement::NightlyJob"

payroll_nightly_job:
  cron: "*/5 * * * *" # run every 5 minutes
  class: "Payroll::NightlyJob"

bank_fee_nightly_job:
  cron: "*/30 2-23 * * *" # run every 30 minutes
  class: "BankFee::NightlyJob"

fee_engine_hourly_job:
  cron: "0 */1 * * *" # run every 1 hours
  class: "FeeEngine::HourlyJob"

receipt_report_weekly_job:
  cron: "0 0 * * MON" # run first day of each week
  class: "ReceiptReport::WeeklyJob"

receipt_report_monthly_job:
  cron: "0 0 3 * *" # run first day of each month
  class: "ReceiptReport::MonthlyJob"

column_reporting_monthly_job:
  cron: "0 0 1 * *" # run first day of each month
  class: "Column::ReportingJob"

column_statement_monthly_job:
  cron: "0 0 3 * *" # run third day of each month
  class: "Column::StatementJob"

stripe_card_nightly_job:
  cron: "0 7 * * *" # run every 1 day, after import
  class: "StripeCard::NightlyJob"

blazer_checks_nightly_job:
  cron: "0 8 * * *"
  class: "BlazerChecksJob"
  args: { schedule: "1 day" }

refresh_hcb_acronym_expansions_job:
  cron: "*/5 * * * *" # run every 5 minutes
  class: "RefreshHcbAcronymExpansionsJob"

calculate_app_wide_metrics:
  cron: "0 */12 * * *" # run twice a day
  class: "Metric::CalculateAppWideJob"

calculate_stats_metric:
  cron: "0 * * * *" # run every hour
  class: "Metric::CalculateStatsJob"

calculate_subjects_metrics:
  cron: "0 */12 * * *" # run twice a day
  class: "Metric::CalculateSubjectsJob"

ledger_audit_weekly_job:
  cron: "0 0 * * MON" # run first day of each week
  class: "Admin::LedgerAudit::GenerateJob"

send_admin_reminders_job:
  cron: "0 7 * * *" # run at 7am UTC each morning
  class: "SendAdminRemindersJob"

gauge_online_user_count_job:
  cron: "*/5 * * * *" # Every 5 minutes
  class: "Statsd::GaugeOnlineUserCountJob"

user_subordinate_summary_job:
  cron: "0 12 * * mon" # noon UTC every Monday (7am eastern)
  class: "User::SubordinateSummaryJob"

user_sync_to_loops_job:
  cron: "0 7 * * *" # run every 1 day
  class: "User::SyncToLoopsJob"

update_teenager_column_job:
  cron: "0 7 * * *" # run every 1 day
  class: "User::UpdateTeenagerColumnJob"

card_grant_expiration_job:
  cron: "0 7 * * *" # run every 1 day
  class: "CardGrant::ExpirationJob"

card_grant_zero_job:
  cron: "0 12 * * *" # run every 1 day
  class: "CardGrant::ZeroJob"

stripe_service_fee_job:
  cron: "0 0 * * MON" # run first day of each week
  class: "StripeServiceFeeJob"

user_seen_at_history_snapshot_job:
  cron: "0,30 * * * *" # twice every hour
  class: "User::SeenAtHistory::SnapshotJob"

column_sweep_job:
  cron: "0 0 * * MON" # run first day of each week
  class: "Column::SweepJob"

stripe_missed_webhooks_job:
  cron: "0/5 * * * *" # run every 5 minutes
  class: "StripeMissedWebhooksJob"

events_sync_to_airtable_job:
  cron: "0 0 * * *" # run every 1 day
  class: "Event::SyncToAirtableJob"
